/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Cateogory of the account.
 */
export enum Category {
    Asset = "asset",
    Expense = "expense",
    Income = "income",
    Liability = "liability",
    Equity = "equity",
    Unknown = "unknown",
}

/**
 * Status of the account.
 */
export enum Status {
    Active = "active",
    Inactive = "inactive",
    Pending = "pending",
}

/**
 * Type of the account.
 */
export enum TypeT {
    AccountsPayable = "accounts_payable",
    AccountsReceivable = "accounts_receivable",
    Bank = "bank",
    CreditCard = "credit_card",
    FixedAsset = "fixed_asset",
    OtherAsset = "other_asset",
    Liability = "liability",
    Equity = "equity",
    Expense = "expense",
    Income = "income",
    Unknown = "unknown",
}

export class Account extends SpeakeasyBase {
    /**
     * Unique identifier of platform for the account.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "account_id" })
    accountId: string;

    /**
     * Balance of the account.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "balance" })
    balance?: number;

    /**
     * Cateogory of the account.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "category" })
    category?: Category;

    /**
     * Unique identifier of the integration on delta.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "connection_id" })
    connectionId?: string;

    /**
     * Creation date of the return on the integration platform
     */
    @SpeakeasyMetadata()
    @Expose({ name: "created_at" })
    createdAt?: string;

    /**
     * ISO 4217 currency code associated with the account.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "currency" })
    currency?: string;

    /**
     * Description of the account.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "description" })
    description?: string;

    /**
     * The unique identifier of the account.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;

    /**
     * Name of the account.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    /**
     * Nominal code of the account.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "nominal_code" })
    nominalCode?: string;

    /**
     * Status of the account.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status?: Status;

    /**
     * Type of the account.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    type?: TypeT;

    /**
     * Last update on the return of the integration platform
     */
    @SpeakeasyMetadata()
    @Expose({ name: "updated_at" })
    updatedAt?: string;
}
