/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Account } from "./account";
import { Expose, Type } from "class-transformer";

export class AccountCollection extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: Account })
    @Expose({ name: "orders" })
    @Type(() => Account)
    orders?: Account[];
}
