/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

export class LineItems extends SpeakeasyBase {
    /**
     * The platform-specific ID of the line_items.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "platform_id" })
    platformId?: string;

    /**
     * The quantity of the line_item.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "quantity" })
    quantity?: string;
}

export class Orders extends SpeakeasyBase {
    /**
     * The platform-specific ID of the order.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "platform_id" })
    platformId?: string;
}

/**
 * The unit of weight of the parcels in this fulfillment.
 */
export enum UnitWeight {
    Kg = "kg",
    G = "g",
    Lb = "lb",
    Oz = "oz",
}

export class Fulfillment extends SpeakeasyBase {
    /**
     * The name of the carrier.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "carrier" })
    carrier?: string;

    /**
     * The date when the order was created. (ISO 8601)
     */
    @SpeakeasyMetadata()
    @Expose({ name: "created_at" })
    createdAt?: string;

    /**
     * The type of delivery (e.g. Same-Day Delivery, Standard 48h).
     */
    @SpeakeasyMetadata()
    @Expose({ name: "delivery_type" })
    deliveryType?: string;

    /**
     * Unique identifier of the fulfillment within delta.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: string;

    /**
     * The currency of the shipping cost. (ISO 4217).
     */
    @SpeakeasyMetadata()
    @Expose({ name: "iso_currency_code" })
    isoCurrencyCode?: string;

    /**
     * The line_items associated with the fulfillment.
     */
    @SpeakeasyMetadata({ elemType: LineItems })
    @Expose({ name: "line_items" })
    @Type(() => LineItems)
    lineItems?: LineItems[];

    /**
     * The orders associated with the fulfillment.
     */
    @SpeakeasyMetadata({ elemType: Orders })
    @Expose({ name: "orders" })
    @Type(() => Orders)
    orders?: Orders[];

    /**
     * The number of parcels of the fulfillment.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "parcels" })
    parcels?: number;

    /**
     * The return tracking number for the fulfillment. Occasionally required to provide by platforms upon fulfillment..
     */
    @SpeakeasyMetadata()
    @Expose({ name: "return_tracking_number" })
    returnTrackingNumber?: string;

    /**
     * The return tracking URL for the fulfillment. Occasionally required to provide by platforms upon fulfillment..
     */
    @SpeakeasyMetadata()
    @Expose({ name: "return_tracking_url" })
    returnTrackingUrl?: string;

    /**
     * The cumulated shipping cost of the order.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "shipping" })
    shipping?: number;

    /**
     * The tracking number for the fulfillment.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "tracking_number" })
    trackingNumber?: string;

    /**
     * The tracking link for the fulfillment..
     */
    @SpeakeasyMetadata()
    @Expose({ name: "tracking_url" })
    trackingUrl?: string;

    /**
     * The unit of weight of the parcels in this fulfillment.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "unit_weight" })
    unitWeight?: UnitWeight;

    /**
     * The date when the order was last updated. (ISO 8601)
     */
    @SpeakeasyMetadata()
    @Expose({ name: "updated_at" })
    updatedAt?: string;

    /**
     * The total weight of the parcels in this fulfillment.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "weight" })
    weight?: number;
}
