/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class InventorySet extends SpeakeasyBase {
    /**
     * The barcode of the inventory.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "barcode" })
    barcode?: string;

    /**
     * Automatic time stamp to compare the upt-to-dateness of existing information.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "change_date" })
    changeDate?: string;

    /**
     * Unique identifier of the connected platform within delta.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "connection_id" })
    connectionId?: string;

    /**
     * Unique identifier of the inventory within delta.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: string;

    /**
     * Unique identifier of the location within delta.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "location_id" })
    locationId?: string;

    /**
     * The platform-specific ID of the location.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "location_platform_id" })
    locationPlatformId: string;

    /**
     * The SKU of the inventory.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "sku" })
    sku: string;

    /**
     * The total stock of the inventory.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "total_stock" })
    totalStock: number;

    /**
     * The platform-specific ID of the inventory.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "variant_id" })
    variantId?: string;
}
