/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

export class JournalEntryLineItems extends SpeakeasyBase {
    /**
     * Unique identifier of the account associated with the journal entry.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "account_id" })
    accountId?: string;

    /**
     * Name of the account associated with the journal entry.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "account_name" })
    accountName?: string;

    /**
     * description of the line item associated with the journal entry.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "description" })
    description?: string;

    /**
     * Amount for the line item. Positive for debit entries and negative for credit entries.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "total_amount" })
    totalAmount?: number;
}

export class JournalEntry extends SpeakeasyBase {
    /**
     * Unique identifier of the integration on delta.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "connection_id" })
    connectionId?: string;

    /**
     * Creation date of the return on the integration platform.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "created_at" })
    createdAt?: string;

    /**
     * ISO 4217 currency code associated with the journal entry.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "currency" })
    currency?: string;

    /**
     * Description of the journal entry.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "description" })
    description?: string;

    /**
     * The unique identifier of the journal entry.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;

    /**
     * Unique identifier of platform for the journal entry.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "journal_id" })
    journalId?: string;

    /**
     * A list of line items associated with the journal entry.
     */
    @SpeakeasyMetadata({ elemType: JournalEntryLineItems })
    @Expose({ name: "line_items" })
    @Type(() => JournalEntryLineItems)
    lineItems?: JournalEntryLineItems[];

    /**
     * Transaction date of the journal entry.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "transaction_date" })
    transactionDate?: string;

    /**
     * Last update on the return of the integration platform.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "updated_at" })
    updatedAt?: string;
}
