/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Fulfillment } from "./fulfillment";
import { Expose, Type } from "class-transformer";

/**
 * Billing address for the order
 */
export class OrderWithoutIdBillingAddress extends SpeakeasyBase {
    /**
     * The first address line of the address.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "address1" })
    address1?: string;

    /**
     * The second address line of the address.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "address2" })
    address2?: string;

    /**
     * The city of the address.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "city" })
    city?: string;

    /**
     * The company name of the customer.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "company_name" })
    companyName?: string;

    /**
     * The country of the address (ISO 3166-1).
     */
    @SpeakeasyMetadata()
    @Expose({ name: "country_code" })
    countryCode?: string;

    /**
     * The email address of the customer.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "email" })
    email?: string;

    /**
     * The first name of the customer.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "first_name" })
    firstName?: string;

    /**
     * The last name of the customer.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "last_name" })
    lastName?: string;

    /**
     * The phone number of the customer.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "phone" })
    phone?: string;

    /**
     * The postal code of the address.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "postal_code" })
    postalCode?: string;

    /**
     * the region of the address.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "region" })
    region?: string;

    /**
     * The tax ID of the customer. Only for B2B orders.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "tax_id" })
    taxId?: string;

    /**
     * The tax type for the customer. Only for B2B orders.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "tax_type" })
    taxType?: string;
}

/**
 * Fulfillment status of the order on the connected platform, can be one of - NULL None of the line items in the order have been fulfilled. - FULFILLED Every line item in the order has been fulfilled. - PARTIALLY At least one line item in the order has been fulfilled. - RETURNED Every line item in the order has been returned and the order canceled.
 */
export enum OrderWithoutIdFulfillmentStatus {
    Null = "NULL",
    Fulfilled = "FULFILLED",
    Partially = "PARTIALLY",
    Returned = "RETURNED",
}

/**
 * Inventory.
 */
export class OrderWithoutIdLineItemsInventory extends SpeakeasyBase {}

export class OrderWithoutIdLineItems extends SpeakeasyBase {
    /**
     * The barcode for the item.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "barcode" })
    barcode?: string;

    /**
     * The country of origin of the item. (ISO 3166-1)
     */
    @SpeakeasyMetadata()
    @Expose({ name: "country_of_origin" })
    countryOfOrigin?: string;

    /**
     * Creation date of the line item.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "created_at" })
    createdAt?: string;

    /**
     * The delivery time of the item in business days.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "delivery_time" })
    deliveryTime?: number;

    /**
     * The fulfillment status of the order line item on the connected platform.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "fulfillment_status" })
    fulfillmentStatus?: string;

    /**
     * Unique identifier of the line item within delta.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: number;

    /**
     * Inventory.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "inventory" })
    @Type(() => OrderWithoutIdLineItemsInventory)
    inventory?: OrderWithoutIdLineItemsInventory;

    /**
     * The currency of the item. (ISO 4217).
     */
    @SpeakeasyMetadata()
    @Expose({ name: "iso_currency_code" })
    isoCurrencyCode?: string;

    /**
     * The name of the item.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    /**
     * The platform-specific ID of the product.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "platform_id" })
    platformId?: string;

    /**
     * The quantity of sold items of the variant.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "quantity" })
    quantity?: number;

    /**
     * Boolean flag whether the item requires shipping.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "requires_shipping" })
    requiresShipping?: boolean;

    /**
     * The serial number of the item.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "serial_number" })
    serialNumber?: string;

    /**
     * The SKU of the item.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "sku" })
    sku?: string;

    /**
     * The total price of the sold items of the variant before taxes.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "subtotal_price" })
    subtotalPrice?: number;

    /**
     * The tax rate for the line item.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "tax_rate" })
    taxRate?: number;

    /**
     * The total discount applied to the sold items of the variant.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "total_discount" })
    totalDiscount?: number;

    /**
     * The total price of the sold items of the variant.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "total_price" })
    totalPrice?: number;

    /**
     * The total taxes associated with the line item.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "total_tax" })
    totalTax?: number;

    /**
     * The unit cost of the item.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "unit_cost" })
    unitCost?: number;

    /**
     * The unit of the weight of the item.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "unit_weight" })
    unitWeight?: string;

    /**
     * Updated date of the line item.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "updated_at" })
    updatedAt?: string;

    /**
     * The platform-specific ID of the variant. Equals platform_id if the product has no variants.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "variant_id" })
    variantId?: string;

    /**
     * The weight of the item.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "weight" })
    weight?: number;
}

/**
 * Payment status of the order on the connected platform.
 */
export enum OrderWithoutIdPaymentStatus {
    Payed = "PAYED",
    NotPayed = "NOT_PAYED",
    Lost = "LOST",
}

/**
 * Billing address for the order
 */
export class OrderWithoutIdShippingAddress extends SpeakeasyBase {
    /**
     * The first address line of the address.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "address1" })
    address1?: string;

    /**
     * The second address line of the address.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "address2" })
    address2?: string;

    /**
     * The city of the address.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "city" })
    city?: string;

    /**
     * The company name of the customer.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "company_name" })
    companyName?: string;

    /**
     * The country of the address (ISO 3166-1).
     */
    @SpeakeasyMetadata()
    @Expose({ name: "country_code" })
    countryCode?: string;

    /**
     * The email address of the customer.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "email" })
    email?: string;

    /**
     * The first name of the customer.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "first_name" })
    firstName?: string;

    /**
     * The last name of the customer.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "last_name" })
    lastName?: string;

    /**
     * The phone number of the customer.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "phone" })
    phone?: string;

    /**
     * The postal code of the address.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "postal_code" })
    postalCode?: string;

    /**
     * the region of the address.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "region" })
    region?: string;
}

/**
 * Status of the order on the connected platform.
 */
export enum OrderWithoutIdStatus {
    Open = "OPEN",
    Closed = "CLOSED",
    Cancelled = "CANCELLED",
}

export class OrderWithoutId extends SpeakeasyBase {
    /**
     * Billing address for the order
     */
    @SpeakeasyMetadata()
    @Expose({ name: "billing_address" })
    @Type(() => OrderWithoutIdBillingAddress)
    billingAddress?: OrderWithoutIdBillingAddress;

    /**
     * Name of the channel on the platform.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "channel" })
    channel?: string;

    /**
     * The channel-specific ID of the order.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "channel_id" })
    channelId?: string;

    /**
     * Unique identifier of the integration on delta.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "connection_id" })
    connectionId?: string;

    /**
     * Creation date of the order on the integration platform.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "created_at" })
    createdAt?: string;

    /**
     * The discount codes used in the order.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "discount_codes" })
    discountCodes?: string;

    /**
     * Fulfillment status of the order on the connected platform, can be one of - NULL None of the line items in the order have been fulfilled. - FULFILLED Every line item in the order has been fulfilled. - PARTIALLY At least one line item in the order has been fulfilled. - RETURNED Every line item in the order has been returned and the order canceled.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "fulfillment_status" })
    fulfillmentStatus?: OrderWithoutIdFulfillmentStatus;

    /**
     * Fulfillments of the order
     */
    @SpeakeasyMetadata({ elemType: Fulfillment })
    @Expose({ name: "fulfillments" })
    @Type(() => Fulfillment)
    fulfillments?: Fulfillment[];

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: number;

    /**
     * The date of the invoice associated with the order.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "invoice_date" })
    invoiceDate?: string;

    /**
     * The number of the invoice associated with the order.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "invoice_number" })
    invoiceNumber?: string;

    /**
     * The currency of the order. (ISO 4217).
     */
    @SpeakeasyMetadata()
    @Expose({ name: "iso_currency_code" })
    isoCurrencyCode?: string;

    /**
     * Items of the order
     */
    @SpeakeasyMetadata({ elemType: OrderWithoutIdLineItems })
    @Expose({ name: "line_items" })
    @Type(() => OrderWithoutIdLineItems)
    lineItems?: OrderWithoutIdLineItems[];

    /**
     * The readable human order id on the connected platform.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "order_number" })
    orderNumber?: string;

    /**
     * The payment method used for the order.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "payment_method" })
    paymentMethod?: string;

    /**
     * Payment status of the order on the connected platform.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "payment_status" })
    paymentStatus?: OrderWithoutIdPaymentStatus;

    /**
     * Name of the connected platform.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "platform" })
    platform?: string;

    /**
     * The platform-specific ID of the order.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "platform_id" })
    platformId?: string;

    /**
     * Billing address for the order
     */
    @SpeakeasyMetadata()
    @Expose({ name: "shipping_address" })
    @Type(() => OrderWithoutIdShippingAddress)
    shippingAddress?: OrderWithoutIdShippingAddress;

    /**
     * Status of the order on the connected platform.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status?: OrderWithoutIdStatus;

    /**
     * The total price of the order before taxes.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "subtotal_price" })
    subtotalPrice?: number;

    /**
     * The tax rate for the order.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "tax_rate" })
    taxRate?: number;

    /**
     * The cumulated discounts applied to the total price.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "total_order_discount" })
    totalOrderDiscount?: number;

    /**
     * The total price of the order.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "total_price" })
    totalPrice?: number;

    /**
     * The total shipping cost of the order.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "total_shipping" })
    totalShipping?: number;

    /**
     * The cumulated shipping discounts of the order.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "total_shipping_discount" })
    totalShippingDiscount?: number;

    /**
     * The total taxes associated with the order.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "total_tax" })
    totalTax?: number;

    /**
     * The sum of all line item weights.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "total_weight" })
    totalWeight?: number;

    /**
     * The unit of the combined line item weights.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "unit_weight" })
    unitWeight?: string;

    /**
     * Updated date of the order in delta.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "updated_at" })
    updatedAt?: string;
}
