/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * One of cash, card, or other.
 */
export enum TransactionPaymentMethod {
    Card = "card",
    Cash = "cash",
    Other = "other",
}

/**
 * One of success, failed, pending, canceled, refunded, or other.
 */
export enum TransactionStatus {
    Success = "success",
    Failed = "failed",
    Pending = "pending",
    Canceled = "canceled",
    Refunded = "refunded",
    Other = "other",
}

/**
 * One of sale, refund, or other.
 */
export enum TransactionType {
    Sale = "sale",
    Refunt = "refunt",
    Other = "other",
}

export class Transaction extends SpeakeasyBase {
    /**
     * Unique identifier of the integration on delta.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "connection_id" })
    connectionId?: string;

    /**
     * The date when the transaction was created. (ISO 8601)
     */
    @SpeakeasyMetadata()
    @Expose({ name: "created_at" })
    createdAt?: string;

    /**
     * The unique identifier of the transaction
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: string;

    /**
     * The currency of the transaction. (ISO 4217)
     */
    @SpeakeasyMetadata()
    @Expose({ name: "iso_currency_code" })
    isoCurrencyCode?: string;

    /**
     * The platform-specific ID of the associated order.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "order_id" })
    orderId?: string;

    /**
     * The gateway associated with the transaction.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "payment_gateway" })
    paymentGateway?: string;

    /**
     * One of cash, card, or other.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "payment_method" })
    paymentMethod?: TransactionPaymentMethod;

    /**
     * The platform-specific ID of the transaction.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "platform_id" })
    platformId?: string;

    /**
     * One of success, failed, pending, canceled, refunded, or other.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status?: TransactionStatus;

    /**
     * The amount of the transaction.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "total_amount" })
    totalAmount?: number;

    /**
     * One of sale, refund, or other.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    type?: TransactionType;

    /**
     * The date when the transaction was last updated. (ISO 8601)
     */
    @SpeakeasyMetadata()
    @Expose({ name: "updated_at" })
    updatedAt?: string;
}
