/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class GetAccountByIdRequest extends SpeakeasyBase {
    /**
     * The unique identifier of the account
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=accountId" })
    accountId: string;
}

export class GetAccountByIdResponse extends SpeakeasyBase {
    /**
     * The account corresponding to the provided `accountId`
     */
    @SpeakeasyMetadata()
    account?: shared.Account;

    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
