/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class GetInvetoryByIdRequest extends SpeakeasyBase {
    /**
     * The unique identifier of the inventory
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=inventoryId" })
    inventoryId: string;
}

export class GetInvetoryByIdResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * The inventory corresponding to the provided `inventoryId`
     */
    @SpeakeasyMetadata()
    inventory?: shared.Inventory;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
