/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class GetLocationByIdRequest extends SpeakeasyBase {
    /**
     * The unique identifier of the location
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=location_id" })
    locationId: string;
}

export class GetLocationByIdResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * The inventory corresponding to the provided `locationId`
     */
    @SpeakeasyMetadata()
    location?: shared.Location;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
