/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class GetProductByIdRequest extends SpeakeasyBase {
    /**
     * The unique identifier of the product
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=productId" })
    productId: string;
}

export class GetProductByIdResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * The product corresponding to the provided `productId`
     */
    @SpeakeasyMetadata()
    product?: shared.Product;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
