/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class GetReturnByIdRequest extends SpeakeasyBase {
    /**
     * The unique identifier of the return
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=returnId" })
    returnId: string;
}

export class GetReturnByIdResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * The return corresponding to the provided `returnId`
     */
    @SpeakeasyMetadata()
    return?: shared.Return;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
