/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class GetTransactionByIdRequest extends SpeakeasyBase {
    /**
     * Get a specific transaction
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=transactionId" })
    transactionId: string;
}

export class GetTransactionByIdResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * The transaction corresponding to the provided `transactionId`
     */
    @SpeakeasyMetadata()
    transaction?: shared.Transaction;
}
